queue_rules:
  - name: default
    conditions:
      - "check-success=test"
pull_request_rules:
  - name: automatic merge for Scala Steward
    conditions:
      - author=tna-digital-archiving-jenkins
      - "check-success=test"
      - or:
          - files=build.sbt
          - files~=^(!?project/)
          - files=version.sbt
    actions:
      review:
        type: APPROVE
        message: Automatically approving Scala Steward
      queue:
        name: default
