name: Deploy if not a version bump PR
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - run: gh workflow run deploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
