name: Deploy if not a version bump PR
on:
  push:
    branches:
      - fix-validation-issue
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow run deploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
