name: Deploy if not a version bump PR
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: gh workflow run deploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
