name: TDR Deploy Metadata Validation
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/sbt_release.yml@b6ba669dcee7fd4ac089c2e9fb234c48ddd93ab5 # v0.0.15
    with:
      library-name: "Metadata validation"
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
