name: TDR Deploy Metadata Validation
on:
  workflow_dispatch:

permissions: { contents: write, id-token: write }

jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/sbt_release.yml@b98899c2acfaf872e0053671743a5b1284b0dab0 # v0.0.43
    with:
      library-name: "Metadata validation"
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
