name: TDR Run Tests
on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release-*
jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
        if: failure()
        with:
          message: ":warning: Secrets found in repository ${{ inputs.repo-name }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run tests
        run: sbt scalafmtCheckAll test
